services:
  # Mongodb service
  mongo_db: 
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  # App service
  api: 
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      SECRET_KEY: kafkasanq213
      MONGO_URL: mongodb://mongo_db:27017/sellcars
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}